create or replace view CDM_CONSTRAINTS(
	TABLE_NAME,
	FIELD_NAME,
	CONSTRAINT_TEXT,
	CONSTRAINT_ORDER,
	CHANGED_IN_THIS_VERSION,
	SOURCE_SHEET,
	SOURCE_ROW_NUM
) as
SELECT
  UPPER(TRIM(TABLE_NAME)) AS TABLE_NAME,
  UPPER(TRIM(FIELD_NAME)) AS FIELD_NAME,
  CONSTRAINT_TEXT AS CONSTRAINT_TEXT,
  CONSTRAINT_ORDER AS CONSTRAINT_ORDER,
  CHANGED_IN_THIS_VERSION AS CHANGED_IN_THIS_VERSION,
  SHEET_NAME AS SOURCE_SHEET,
  ROW_NUM AS SOURCE_ROW_NUM
FROM CHARACTERIZATION.EDC_REF.CDM_PARSEABLE_RAW
WHERE UPPER(SHEET_NAME) = 'CONSTRAINTS'
  AND TABLE_NAME IS NOT NULL
  AND FIELD_NAME IS NOT NULL
  AND CONSTRAINT_TEXT IS NOT NULL;