create or replace view CDM_VALUESETS(
	TABLE_NAME,
	FIELD_NAME,
	VALUESET_ITEM,
	VALUESET_ITEM_DESCRIPTOR,
	VALUESET_ITEM_ORDER,
	CHANGED_IN_THIS_VERSION,
	SOURCE_SHEET,
	SOURCE_ROW_NUM
) as
SELECT
  UPPER(TRIM(TABLE_NAME)) AS TABLE_NAME,
  UPPER(TRIM(FIELD_NAME)) AS FIELD_NAME,
  TRIM(VALUESET_ITEM) AS VALUESET_ITEM,
  VALUESET_ITEM_DESCRIPTOR AS VALUESET_ITEM_DESCRIPTOR,
  TRY_TO_NUMBER(VALUESET_ITEM_ORDER) AS VALUESET_ITEM_ORDER,
  CHANGED_IN_THIS_VERSION AS CHANGED_IN_THIS_VERSION,
  SHEET_NAME AS SOURCE_SHEET,
  ROW_NUM AS SOURCE_ROW_NUM
FROM CHARACTERIZATION.EDC_REF.CDM_PARSEABLE_RAW
WHERE UPPER(SHEET_NAME) = 'VALUESETS'
  AND TABLE_NAME IS NOT NULL
  AND FIELD_NAME IS NOT NULL
  AND VALUESET_ITEM IS NOT NULL;