create or replace view DC_SUMMARY(
	EDC_TABLE,
	DESCRIPTION,
	CATEGORY,
	CHECK_TYPE,
	ROW_NUM_STR,
	ROW_NUM,
	PART,
	QUERY_PACKAGE
) as
SELECT
  EDC_TABLE_S_ AS edc_table,
  DATA_CHECK_DESCRIPTION AS description,
  CATEGORY AS category,
  TYPE AS check_type,
  DATA_CHECK_NUM AS row_num_str,
  TRY_TO_DECIMAL(DATA_CHECK_NUM, 10, 2) AS row_num,
  LOWER(DCPART_MACRO_VALUE) AS part,
  QUERY_PACKAGE AS query_package
FROM CHARACTERIZATION.EDC_REF.DC_SUMMARY_RAW
WHERE TRY_TO_DECIMAL(DATA_CHECK_NUM, 10, 2) IS NOT NULL;